CXXFLAGS = -g -std=c++17 -Wall -Wextra
LDFLAGS = -lsfml-graphics -lsfml-window -lsfml-system

# sfml: game.o
# 	g++ $(CXXFLAGS) $^ $(LDFLAGS) -o $@

# game.o: game.cc
# 	g++ -c $(CXXFLAGS) $<

# .PHONY: clean
# clean:
# 	rm -f *.o sfml
